export function enhanceCommercialPanel(response: Response): Response {
    const contentType = response.headers.get('content-type') || '';
    if (!contentType.includes('text/html')) return response;
    const script = `<script>(function(){
const GB=1073741824;
function el(id){return document.getElementById(id)}
function addControls(){
 const form=document.querySelector('#tab-users .add-user-form');
 if(form&&!el('addUserQuota')){
  form.insertAdjacentHTML('beforeend','<div class="form-group" style="margin:0;"><label class="form-label">Traffic Quota (GB)</label><input class="neon-input" type="number" id="addUserQuota" value="0" min="0" step="0.01" title="0 = unlimited"></div><div class="form-group" style="margin:0;"><label class="form-label">Devices</label><select class="neon-input" id="addUserConnections"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div>');
 }
 const modal=el('userEditModal');
 if(modal&&!el('editUserQuota')){
  const note=el('editUserNote');
  note&&note.parentElement.insertAdjacentHTML('afterend','<div class="form-group"><label class="form-label">Traffic Quota (GB)</label><input class="neon-input" type="number" id="editUserQuota" min="0" step="0.01" title="0 = unlimited"></div><div class="form-group"><label class="form-label">Devices</label><select class="neon-input" id="editUserConnections"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div><label class="toggle-label"><input type="checkbox" id="editUserResetUsage"><span class="toggle-switch"></span> Reset traffic usage</label>');
 }
 const table=document.querySelector('.users-table thead tr');
 if(table&&table.children.length===5){table.insertAdjacentHTML('beforeend','<th>Traffic</th><th>Devices</th>')}
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function status(u){if(!u.active)return '<span style="color:gray;">⏸ Disabled</span>';if(new Date(u.expiresAt)<new Date())return '<span style="color:red;">❌ Expired</span>';if(u.quotaBytes>0&&(u.usedBytes||0)>=u.quotaBytes)return '<span style="color:#f59e0b;">🚫 Quota</span>';return '<span style="color:green;">✅ Active</span>'}
window.renderUsers=function(users){const tbody=el('users-tbody');if(!tbody)return;if(!users.length){tbody.innerHTML='<tr><td colspan="7" class="text-muted text-sm" style="text-align:center;padding:24px;">No users found.</td></tr>';return;}tbody.innerHTML=users.map(u=>{const url=window.origin+'/sub/user/'+u.subPath;const quota=u.quotaGb>0?u.quotaGb.toFixed(2)+' GB':'Unlimited';const used=(u.usedGb||0).toFixed(2)+' GB';const traffic=u.quotaGb>0?used+' / '+quota:used+' / Unlimited';return '<tr><td><b>'+esc(u.username)+'</b></td><td>'+new Date(u.expiresAt).toLocaleDateString()+'</td><td>'+status(u)+'</td><td>'+esc(u.note||'-')+'</td><td>'+traffic+'</td><td>'+(u.activeSessions||0)+' / '+(u.maxConnections||1)+'</td><td class="actions-cell"><button class="action-btn" title="Copy subscription URL" onclick="copyUserSub(\''+esc(url)+'\')">📋</button><button class="action-btn" title="Edit user" onclick="openUserEdit(\''+esc(u.username)+'\')">✏️</button><button class="action-btn danger" title="Delete user" onclick="deleteUser(\''+esc(u.username)+'\')">🗑️</button></td></tr>';}).join('')}
window.addUser=async function(){const username=el('addUserUsername').value.trim(),days=parseInt(el('addUserDays').value)||30,note=el('addUserNote').value.trim(),quotaGb=parseFloat(el('addUserQuota')?.value||0),maxConnections=parseInt(el('addUserConnections')?.value||1);if(!/^[a-zA-Z0-9_]{3,20}$/.test(username)){showToast('Invalid username.','error');return}if(quotaGb<0||maxConnections<1||maxConnections>5){showToast('Invalid quota or device limit.','error');return}try{document.body.style.cursor='wait';const r=await fetch('/panel/users',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,days,note,quotaGb,maxConnections})});const d=await r.json();if(!d.success){showToast(d.message||'Failed to create user.','error');return}el('addUserUsername').value='';el('addUserNote').value='';showToast('User created.','success');loadUsers()}catch(e){showToast('Failed to create user.','error')}finally{document.body.style.cursor='default'}}
window.openUserEdit=async function(username){window.editingUsername=username;try{document.body.style.cursor='wait';const r=await fetch('/panel/users/'+encodeURIComponent(username),{credentials:'include'}),d=await r.json();if(!d.success){showToast('User not found.','error');return}const u=d.body;el('editUserUsername').textContent=u.username;el('editUserDays').value=0;el('editUserNote').value=u.note||'';el('editUserActive').value=u.active?'true':'false';el('editUserQuota').value=u.quotaGb||0;el('editUserConnections').value=u.maxConnections||1;el('editUserResetUsage').checked=false;el('userEditModal').style.display='flex';document.body.style.overflow='hidden'}catch(e){showToast('Failed to load user.','error')}finally{document.body.style.cursor='default'}}
window.saveUserEdit=async function(){if(!window.editingUsername)return;const days=parseInt(el('editUserDays').value)||0,note=el('editUserNote').value.trim(),active=el('editUserActive').value==='true',quotaGb=parseFloat(el('editUserQuota').value||0),maxConnections=parseInt(el('editUserConnections').value||1),resetUsage=el('editUserResetUsage').checked;try{document.body.style.cursor='wait';const r=await fetch('/panel/users/'+encodeURIComponent(window.editingUsername),{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({days,note,active,quotaGb,maxConnections,resetUsage})}),d=await r.json();if(!d.success){showToast(d.message||'Failed to update user.','error');return}showToast('User updated.','success');closeUserEdit();loadUsers()}catch(e){showToast('Failed to update user.','error')}finally{document.body.style.cursor='default'}}
addControls();
const oldLoad=window.loadUsers;window.loadUsers=async function(){try{const r=await fetch('/panel/users',{credentials:'include'}),d=await r.json();if(d.success)window.renderUsers(d.body||[])}catch(e){console.error('Load users error:',e)}};window.loadUsers();
})();</script>`;
    return new HTMLRewriter().on('body',{element(element){element.append(script,{html:true});}}).transform(response);
}
