export function bootstrapCommercialUI(response: Response): Response {
    const contentType = response.headers.get('content-type') || '';
    if (!contentType.includes('text/html')) return response;

    const script = `<script>(function(){
const C='__bpbCommercialBootstrapV3';if(window[C])return;window[C]=true;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));
function ensureAdd(){const f=document.querySelector('#tab-users .add-user-form');if(!f)return;if(!$('addUserQuota'))f.insertAdjacentHTML('beforeend','<div class="form-group" style="margin:0"><label class="form-label">Traffic Quota (GB)</label><input class="neon-input" type="number" id="addUserQuota" value="0" min="0" step="0.01" title="0 = unlimited"></div>');if(!$('addUserConnections'))f.insertAdjacentHTML('beforeend','<div class="form-group" style="margin:0"><label class="form-label">Devices</label><select class="neon-input" id="addUserConnections"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div>');}
function ensureEdit(){const n=$('editUserNote');if(!n||$('editUserQuota'))return;n.parentElement.insertAdjacentHTML('afterend','<div class="form-group"><label class="form-label">Traffic Quota (GB)</label><input class="neon-input" type="number" id="editUserQuota" min="0" step="0.01" title="0 = unlimited"></div><div class="form-group"><label class="form-label">Devices</label><select class="neon-input" id="editUserConnections"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div><label class="toggle-label"><input type="checkbox" id="editUserResetUsage"><span class="toggle-switch"></span> Reset traffic usage</label><label class="toggle-label"><input type="checkbox" id="editUserResetState"><span class="toggle-switch"></span> Reset active connections</label>');}
function ensureHeader(){const h=document.querySelector('.users-table thead tr');if(h&&h.children.length===5)h.insertAdjacentHTML('beforeend','<th>Traffic</th><th>Devices</th>');}
function boot(){ensureAdd();ensureEdit();ensureHeader();}
window.addUser=async function(){const username=$('addUserUsername')?.value.trim(),days=parseInt($('addUserDays')?.value)||30,note=$('addUserNote')?.value.trim()||'',quotaGb=parseFloat($('addUserQuota')?.value||0),maxConnections=parseInt($('addUserConnections')?.value||1);if(!/^[a-zA-Z0-9_]{3,20}$/.test(username)){showToast('Invalid username.','error');return}if(quotaGb<0||maxConnections<1||maxConnections>5){showToast('Invalid quota or device limit.','error');return}try{const r=await fetch('/panel/users',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,days,note,quotaGb,maxConnections})}),d=await r.json();if(!d.success){showToast(d.message||'Failed to create user.','error');return}if($('addUserUsername'))$('addUserUsername').value='';if($('addUserNote'))$('addUserNote').value='';if($('addUserQuota'))$('addUserQuota').value='0';showToast('User created.','success');await window.loadUsers()}catch(e){showToast('Failed to create user.','error')}};
window.loadUsers=async function(){try{const r=await fetch('/panel/users',{credentials:'include'}),d=await r.json();if(!d.success){showToast(d.message||'Failed to load users.','error');return}const users=d.body||[],t=$('users-tbody');if(!t)return;ensureHeader();t.innerHTML=users.length?users.map(u=>{const q=u.quotaGb>0?Number(u.quotaGb).toFixed(2)+' GB':'Unlimited',used=Number(u.usedGb||0).toFixed(2)+' GB';const st=!u.active?'<span style="color:gray">⏸ Disabled</span>':new Date(u.expiresAt)<new Date()?'<span style="color:red">❌ Expired</span>':u.quotaBytes>0&&(u.usedBytes||0)>=u.quotaBytes?'<span style="color:#f59e0b">🚫 Quota</span>':'<span style="color:green">✅ Active</span>';return '<tr><td><b>'+esc(u.username)+'</b></td><td>'+new Date(u.expiresAt).toLocaleDateString()+'</td><td>'+st+'</td><td>'+esc(u.note||'-')+'</td><td>'+used+' / '+q+'</td><td>'+(u.activeSessions||0)+' / '+(u.maxConnections||1)+'</td><td class="actions-cell"><button class="action-btn" title="Copy subscription URL" onclick="copyUserSub(\''+esc(window.origin+'/sub/user/'+u.subPath)+'\')">📋</button><button class="action-btn" title="Edit user" onclick="openUserEdit(\''+esc(u.username)+'\')">✏️</button><button class="action-btn danger" title="Delete user" onclick="deleteUser(\''+esc(u.username)+'\')">🗑️</button></td></tr>'}).join(''):'<tr><td colspan="7" class="text-muted text-sm" style="text-align:center;padding:24px">No users found.</td></tr>'}catch(e){console.error('Commercial users load error:',e)}};
window.openUserEdit=async function(username){try{ensureEdit();const r=await fetch('/panel/users/'+encodeURIComponent(username),{credentials:'include'}),d=await r.json();if(!d.success){showToast('User not found.','error');return}const u=d.body||{};window.editingUsername=username;$('editUserUsername').textContent=u.username||username;$('editUserDays').value=0;$('editUserNote').value=u.note||'';$('editUserActive').value=u.active?'true':'false';$('editUserQuota').value=u.quotaGb||0;$('editUserConnections').value=u.maxConnections||1;$('editUserResetUsage').checked=false;$('editUserResetState').checked=false;$('userEditModal').style.display='flex';document.body.style.overflow='hidden'}catch(e){showToast('Failed to load user.','error')}};
window.saveUserEdit=async function(){if(!window.editingUsername)return;ensureEdit();const days=parseInt($('editUserDays').value)||0,note=$('editUserNote').value.trim(),active=$('editUserActive').value==='true',quotaGb=parseFloat($('editUserQuota').value||0),maxConnections=parseInt($('editUserConnections').value||1),resetUsage=$('editUserResetUsage').checked,resetState=$('editUserResetState').checked;if(quotaGb<0||maxConnections<1||maxConnections>5){showToast('Invalid quota or device limit.','error');return}try{const r=await fetch('/panel/users/'+encodeURIComponent(window.editingUsername),{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({days,note,active,quotaGb,maxConnections,resetUsage,resetState})}),d=await r.json();if(!d.success){showToast(d.message||'Failed to update user.','error');return}showToast('User updated.','success');if(typeof closeUserEdit==='function')closeUserEdit();await window.loadUsers()}catch(e){showToast('Failed to update user.','error')}};
const observer=new MutationObserver(boot);observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{boot();window.loadUsers()});else{boot();setTimeout(()=>window.loadUsers(),0)}
})();</script>`;
    return new HTMLRewriter().on('body', { element(element) { element.append(script, { html: true }); } }).transform(response);
}
